font:
  normal:
    family: mononokiNerd Font
  size: 12.0

colors:
  bright:
    black: '#686868'
    blue: '#5CCFE6'
    cyan: '#95E6CB'
    green: '#A6CC70'
    magenta: '#FFEE99'
    red: '#F27983'
    white: '#FFFFFF'
    yellow: '#FFCC66'
  normal:
    black: '#191E2A'
    blue: '#73D0FF'
    cyan: '#95E6CB'
    green: '#BAE67E'
    magenta: '#FFD580'
    red: '#FF3333'
    white: '#C7C7C7'
    yellow: '#FFA759'
  primary:
    background: '#202734'
    foreground: '#CBCCC6'

mouse_bindings:
  - { mouse: Right, action: Paste }

selection:
  save_to_clipboard: true
